### ISSUE TITLE
paginated_response of gitlab-3.7.0 causes an exception, if GITLAB URL was entered with trailing slash

### ISSUE THREAD

**Issue by marcelloceschia** [errbit/errbit_github_plugin#12]
the reason is, that next_page in `gitlab-3.7.0/lib/gitlab/paginated_response.rb` replace the enpoint part in `@links.next` with an empty string to get the path without domain.
If the GITLAB URL is saved with trailing slash (e.g. https://gitlab.example.com/) gitlab_endpoint in `errbit_gitlab_plugin-1.0.1/lib/errbit_gitlab_plugin/issue_tracker.rb` will format the endpoint as https://gitlab.example.com//api/v3 and this can not be found in the `@links.next` string

**Comment by stevecrozz** [comment]
This seems like an errbit_gitlab_plugin issue, would you mind raising it at https://github.com/brandedcrate/errbit_gitlab_plugin ?

**Comment by marcelloceschia** [comment]
@stevecrozz Of course, sorry I've mix up the repository
