### ISSUE TITLE
unable to run tests

### ISSUE THREAD

**Issue by mfrederickson** [errbit/errbit_github_plugin#9]
Could someone please educate me on how to run tests for this repo?  I cloned the repo and ran `bundle install` and then `rspec` and I get the following.  I'm using rvm, ruby 2.1.5, and have rails 4.2.1.5.  I don't want to submit PRs if I cannot run tests.  Thanks.

```
mfrederickson@fenris:~/projects/errbit_github_plugin$ rspec
/home/mfrederickson/projects/errbit_github_plugin/spec/spec_helper.rb:17:in `require': cannot load such file -- active_support/all (LoadError)
	from /home/mfrederickson/projects/errbit_github_plugin/spec/spec_helper.rb:17:in `<top (required)>'
```

However, when I run `irb` I can require it just fine...

```
mfrederickson@fenris:~/projects/errbit_github_plugin$ irb
2.1.5 :001 > require 'active_support/all'
 => true 
```

**Comment by stevecrozz** [comment]
It looks like there's a couple of issues, one of which is activesupport not being a dependency in the gemspec. I'm working on that plus travis integration here:
https://github.com/errbit/errbit_github_plugin/pull/10

The build has been in progress for a while, but if you want to get going you can check out the branch and 'bundle exec rspec' to see the specs passing.

**Comment by mfrederickson** [comment]
Thanks.  I'll look into it....

**Comment by stevecrozz** [comment]
Looks like you got this going. I just also added the build status badge to the readme.
